title: Technical Writing Portfolio
description: A Technical Writing Portfolio for Spencer Krigbaum
theme: just-the-docs

url: https://Skrigbaum.github.io/writing-portfolio

aux_links:
  Template Repository: https://github.com/Skrigbaum/writing-portfolio
